/**
 * Hazelcast Monitor 0.0.1 DTOs
 * -------------------------------------
 * This file is automatically generated by TypescriptMapper.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
import { AbstractTopicDTO } from './topics.dto';
import { ProductDTO } from './topic-products.dto';
export interface AbstractMessageDTO {
	messageType: 'subscribe' | 'update_subscription' | 'unsubscribe' | 'pull_subscription' | 'authenticate' | 'check_authentication' | 'subscribe_response' | 'update_subscription_response' | 'notice' | 'authenticate_response' | 'check_authentication_response' | 'error';
	messageId?: number;
}

export interface AuthenticateRequestDTO extends AbstractMessageDTO {
	messageType: 'authenticate';
	groupName: string;
	groupPassword: string;
}

export interface AuthenticateResponseDTO extends AbstractMessageDTO {
	messageType: 'authenticate_response';
	groupName: string;
	error?: string;
}

export interface CheckAuthenticationRequestDTO extends AbstractMessageDTO {
	messageType: 'check_authentication';
	groupName: string;
}

export interface CheckAuthenticationResponseDTO extends AbstractMessageDTO {
	messageType: 'check_authentication_response';
	groupName: string;
	authenticated: boolean;
}

export interface ErrorMessageDTO extends AbstractMessageDTO {
	messageType: 'error';
	errors: string[];
}

export interface PullSubscriptionRequestDTO extends AbstractMessageDTO {
	messageType: 'pull_subscription';
	subscriptionId: number;
}

export interface SubscribeRequestDTO extends AbstractMessageDTO {
	messageType: 'subscribe';
	frequency: number;
	topic: AbstractTopicDTO;
	parameters?: { [ index: string ]: string };
}

export interface SubscribeResponseDTO extends AbstractMessageDTO {
	messageType: 'subscribe_response';
	subscriptionId: number;
	topic: AbstractTopicDTO;
}

export interface SubscriptionNoticeResponseDTO<T extends ProductDTO> extends AbstractMessageDTO {
	messageType: 'notice';
	topicType: string;
	subscriptionId: number;
	notice: T;
}

export interface UnsubscribeRequestDTO extends AbstractMessageDTO {
	messageType: 'unsubscribe';
	subscriptionId: number;
}

export interface UpdateSubscriptionRequestDTO extends AbstractMessageDTO {
	messageType: 'update_subscription';
	subscriptionId: number;
	parameters: { [ index: string ]: string };
}

export interface UpdateSubscriptionResponseDTO extends AbstractMessageDTO {
	messageType: 'update_subscription_response';
	subscriptionId: number;
	parameters: { [ index: string ]: string };
	error?: string;
}
