/**
 * Hazelcast Monitor 0.0.1 DTOs
 * -------------------------------------
 * This file is automatically generated by TypescriptMapper.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
export interface EnvironmentVariableDTO {
	name: string;
	value: string;
}

export interface SubscriptionRegistryStatisticsDTO {
	subscriptions: SubscriptionStatisticsDTO[];
}

export interface SubscriptionStatisticsDTO {
	id: number;
	topic: string;
}
