version: 2
jobs:
  build_prepare:
    docker:
      - image: daniloarcidiacono/ci-java-node:0.4.0

    working_directory: ~/hazelcast-monitor

    steps:
      - checkout

      - persist_to_workspace:
          root: '~'
          paths:
            - hazelcast-monitor

  build_fe:
    docker:
      - image: daniloarcidiacono/ci-java-node:0.4.0

    working_directory: ~/hazelcast-monitor

    steps:
      - attach_workspace:
          at: '~'

      - restore_cache:
          key: npm-dependency-cache-{{ checksum "hazelcast-monitor-webapp/package.json" }}

      - run:
          name: Install npm packages
          command: cd hazelcast-monitor-webapp && npm install

      - save_cache:
          key: npm-dependency-cache-{{ checksum "hazelcast-monitor-webapp/package.json" }}
          paths:
            - hazelcast-monitor-webapp/node_modules

      - run:
          name: Build prod
          command: cd hazelcast-monitor-webapp && npm run build-prod

      - run:
          name: Zipping
          command: cd hazelcast-monitor-webapp/dist && zip -r hazelcast-monitor-$CIRCLE_TAG.zip hazelcast-monitor

      - run:
          name: Create artifacts directory
          command: mkdir ./artifacts && cp hazelcast-monitor-webapp/dist/hazelcast-monitor-$CIRCLE_TAG.zip ./artifacts

      - store_artifacts:
          path: artifacts
          destination: artifacts-fe

  build_be:
    docker:
      - image: daniloarcidiacono/ci-java-node:0.4.0

    working_directory: ~/hazelcast-monitor

    steps:
      - attach_workspace:
          at: '~'

      - restore_cache:
          key: hazelcast-monitor-{{ checksum "pom.xml" }}

      - run:
          command: mvn verify dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: hazelcast-monitor-{{ checksum "pom.xml" }}

      - run:
          command: mvn clean package -Pdocs

      - deploy:
          name: Create GitHub release
          command: |
            hub release create -d \
                               -a hazelcast-monitor-agent/target/hazelcast-monitor-agent-*-javadoc.jar \
                               -a hazelcast-monitor-starter-java-websockets/target/hazelcast-monitor-starter-java-websockets-*-javadoc.jar \
                               -a hazelcast-monitor-starter-spring/target/hazelcast-monitor-starter-spring-*-javadoc.jar \
                               -F CHANGELOG_LATEST.md $CIRCLE_TAG

      - run:
          name: Create artifacts directory
          command: |
            shopt -s globstar
            mkdir ./artifacts
            cp **/target/*.jar ./artifacts

      - store_artifacts:
          path: artifacts
          destination: artifacts-be

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_prepare:
          filters:
            tags:
              only: /^pre.*/
            branches:
              ignore: /.*/

      - build_fe:
          requires:
            - build_prepare
          filters:
            tags:
              only: /^pre.*/
            branches:
              ignore: /.*/

      - build_be:
          requires:
            - build_prepare
          filters:
            tags:
              only: /^pre.*/
            branches:
              ignore: /.*/
