server:
  servlet:
    contextPath: /monitor
  port: 7000

spring:
  main:
    banner-mode: "off"

logging:
  level:
    io.github.daniloarcidiacono.hazelcast.monitor: DEBUG

monitor:
  threads:
    threadPoolSize: 2

  websocket:
    # Must not contain an eventual contextPath
    endpoint: "/ws"
    allowed-origins:
      - "*"

sampleapp:
  instanceName: "dev"
  groupName: "group"
  groupPassword: "pass"
  managementCenterEnabled: false
  managementCenterUrl: "http://localhost:8080/mancenter"
